# Generated by Django 3.1.2 on 2020-11-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20201111_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squareImage', models.ImageField(default='/ads_image/square_ads_default.png', upload_to='ads_image/')),
                ('reactangleImage', models.ImageField(default='/ads_image/reactangle_ads_default.png', upload_to='ads_image/')),
                ('url', models.URLField(blank=True, null=True)),
                ('estimatedView', models.IntegerField(default=0)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('premium', models.BooleanField(default=False)),
                ('catagories', models.ManyToManyField(blank=True, to='website.Catagory')),
            ],
        ),
    ]
